#!/bin/sh
if [ -z ${1} ];
then
    echo "输入源文件名!"
    exit 1
fi
linenum=`cat ${1} | wc -l`
outfile=${1%.*}.apts
if [ -f "${outfile}" ]; then  
    rm ${outfile} 
fi  
echo "[Expe/PointSet/Ascii/0.2]" >> ${outfile}
echo "property position 3 r32" >> ${outfile}
echo "property radius 1 r32" >> ${outfile}
echo "property normal 3 r32" >> ${outfile}
echo "property color 4 ui8" >> ${outfile}
echo "nofpoints ${linenum}" >> ${outfile}
echo "data" >> ${outfile}
awk '{print $1","$2,","$3";0;"$4","$5","$6";1,1,1,1;0"}' ${1} >> ${outfile}
